# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "remote" {
    organization = "env-v0ok759at59erieho"
    workspaces  {
      name = "scalr-terragrunt-simple"
    }
    hostname = "mainiacp.ape.testenv.scalr.dev"
  }
}
